In [179]:
import numpy as np

In [180]:
import utils
input = utils.GetInput(4)

In [181]:
# input = """7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

# 22 13 17 11  0
#  8  2 23  4 24
# 21  9 14 16  7
#  6 10  3 18  5
#  1 12 20 15 19

#  3 15  0  2 22
#  9 18 13 17  5
# 19  8  7 25 23
# 20 11 10 24  4
# 14 21 16 12  6

# 14 21 17 24  4
# 10 16 15  9 19
# 18  8 23 26 20
# 22 11 13  6  5
#  2  0 12  3  7"""

In [182]:
lines = input.split('\n\n')
len(lines)

lines[1:3]

['38 80 23 60 82\n25 35 28 47 39\n40  0 30 48 76\n32 41 49 69  4\n13 42 89 20 12',
 '76 89 13  5 98\n87 48  2 59 20\n37 88 41 24 57\n16 85 31 73 95\n70 11 93 30 27']

In [183]:
numbers = np.array([int(i) for i in lines[0].split(',')])
numbers

array([50, 68,  2,  1, 69, 32, 87, 10, 31, 21, 78, 23, 62, 98, 16, 99, 65,
       35, 27, 96, 66, 26, 74, 72, 45, 52, 81, 60, 38, 57, 54, 19, 18, 77,
       71, 29, 51, 41, 22,  6, 58,  5, 42, 92, 85, 64, 94, 12, 83, 11, 17,
       14, 37, 36, 59, 33,  0, 93, 34, 70, 97,  7, 76, 20,  3, 88, 43, 47,
        8, 79, 80, 63,  9, 25, 56, 75, 15,  4, 82, 67, 39, 30, 89, 86, 46,
       90, 48, 73, 91, 55, 95, 28, 49, 61, 44, 84, 40, 53, 13, 24])

In [184]:
board = lines[1]
[[int(x) for x in r.split()] for r in board.splitlines()]

[[38, 80, 23, 60, 82],
 [25, 35, 28, 47, 39],
 [40, 0, 30, 48, 76],
 [32, 41, 49, 69, 4],
 [13, 42, 89, 20, 12]]

In [185]:
boards = np.array([[[int(x) for x in r.split()] for r in board.splitlines()] for board in lines[1:]])
boards[:3]

array([[[38, 80, 23, 60, 82],
        [25, 35, 28, 47, 39],
        [40,  0, 30, 48, 76],
        [32, 41, 49, 69,  4],
        [13, 42, 89, 20, 12]],

       [[76, 89, 13,  5, 98],
        [87, 48,  2, 59, 20],
        [37, 88, 41, 24, 57],
        [16, 85, 31, 73, 95],
        [70, 11, 93, 30, 27]],

       [[81, 55, 41, 85, 33],
        [67, 97, 71, 90, 52],
        [19,  3, 79, 66, 14],
        [49, 96, 94, 26, 25],
        [60, 46, 51, 82,  9]]])

In [186]:
check_boards = np.array([[[False]*5]*5] * len(boards))
check_boards[0:3]

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [187]:
board = boards[0]
print(board)
board[:,1]

[[38 80 23 60 82]
 [25 35 28 47 39]
 [40  0 30 48 76]
 [32 41 49 69  4]
 [13 42 89 20 12]]


array([80, 35,  0, 41, 42])

In [188]:
np.argwhere(board == 29)

array([], shape=(0, 2), dtype=int64)

In [199]:
def check_bingo(board):
    for i in range(board.shape[0]):
        if(np.all(board[i,:] == True)):
            return True
    for i in range(board.shape[1]):
        if(np.all(board[:,i] == True)):
            return True

    return False

def calculate_score(board, hits, num):
    return np.sum(board[hits == False]) * num

def score_board(board, numbers):
    count = 0
    hits = np.array([[False]*5]*5)
    for number in numbers:
        count = count + 1
        hits[board == number] = True
        if(check_bingo(hits)):
            return count, calculate_score(board, hits, number)

    return count, -1

score_board(boards[2], numbers)

(70, 33417)

In [200]:
scores = [score_board(board, numbers) for board in boards]
scores

[(71, 35760),
 (63, 36480),
 (70, 33417),
 (56, 19305),
 (37, 38556),
 (66, 38720),
 (74, 10725),
 (69, 3472),
 (51, 10761),
 (32, 11970),
 (56, 17721),
 (55, 26550),
 (52, 7700),
 (65, 702),
 (54, 18432),
 (78, 1920),
 (58, 35433),
 (54, 19368),
 (55, 31565),
 (49, 42247),
 (57, 0),
 (50, 6028),
 (66, 46288),
 (71, 30000),
 (68, 20257),
 (52, 6804),
 (60, 36890),
 (75, 18928),
 (56, 11913),
 (46, 33472),
 (52, 6720),
 (35, 61628),
 (70, 38473),
 (76, 21450),
 (35, 80088),
 (69, 3416),
 (57, 0),
 (60, 27930),
 (58, 46779),
 (69, 2992),
 (20, 87456),
 (73, 3483),
 (62, 3353),
 (64, 8180),
 (53, 13764),
 (61, 50149),
 (47, 72286),
 (62, 3290),
 (56, 18876),
 (61, 41225),
 (56, 28710),
 (79, 20500),
 (57, 0),
 (63, 31084),
 (68, 19787),
 (75, 16016),
 (53, 21793),
 (71, 44560),
 (42, 2895),
 (65, 1359),
 (69, 3888),
 (57, 0),
 (51, 9452),
 (67, 12728),
 (47, 49726),
 (48, 7620),
 (42, 3845),
 (54, 22356),
 (73, 3240),
 (75, 23576),
 (65, 1269),
 (67, 14878),
 (42, 2405),
 (53, 28490),
 (7

In [202]:
sorted_list = sorted(scores)

print('Solution 1:', sorted_list[0])
print('Solution 2:', sorted_list[-1])


Solution 1: (20, 87456)
Solution 2: (81, 15561)
